/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import AppPackage.AnimationClass;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import javafx.animation.Animation;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dhankuwarsisodiya
 */
public class loginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginJFrame
     */
    private static EcoSystem system;
    private static JFrame frame;
    private static MainJFrame mainJFrame;
    private UserAccount userAccount;
    private Enterprise inEnterprise;
    private Organization inOrganization;
    private Network networkEmergency;
    public loginJFrame(EcoSystem system, MainJFrame mainJFrame) {
        initComponents();
        this.setSize(500, 700);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2- this.getSize().width /2, dim.height/2- this.getSize().height /2);
        this.system = system;
        this.frame = this;
        this.mainJFrame = mainJFrame;
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        yellow = new javax.swing.JLabel();
        red = new javax.swing.JLabel();
        lightBlue = new javax.swing.JLabel();
        loginHeading = new javax.swing.JLabel();
        darkBlue = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        skin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yellow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/design2.png"))); // NOI18N
        jPanel1.add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -20, 470, 630));

        red.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/design1.png"))); // NOI18N
        jPanel1.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -90, 580, 450));

        lightBlue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/design3.png"))); // NOI18N
        jPanel1.add(lightBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, 300));

        loginHeading.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        loginHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginHeading.setText("LOGIN");
        jPanel1.add(loginHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 210, 680, 40));

        darkBlue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        darkBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/design5.png"))); // NOI18N
        jPanel1.add(darkBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 290, 510));

        usernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        usernameLabel.setText("Username");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 20));

        passwordLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));
        jPanel1.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 180, 30));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 180, -1));

        loginBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        loginBtn.setText("Log In");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 110, -1));

        cancelBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system admin user account directory if you have the user
        userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);

        inEnterprise=null;
        inOrganization=null;
        networkEmergency = null;
        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                //Step 2.a: check against each enterprise
                System.out.println("Network name --->> " + network.getName());
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                    System.out.println("Enterprise name --->> " + enterprise.getName());
                    userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    networkEmergency = network;
                    if(userAccount==null){
                        //Step 3:check against each organization for each enterprise
                        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                            userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if(userAccount!=null){
                                inEnterprise=enterprise;
                                inOrganization=organization;
                                networkEmergency = network;
                                break;
                            }
                        }

                    }
                    else{
                        inEnterprise=enterprise;
                        break;
                    }
                    if(inOrganization!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
                /*if (networkEmergency != null) {//changed
                    break;
                }*/
            }
        }

        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            AnimationClass anim = new AnimationClass();
            anim.jLabelXLeft(red.getX(), -1000, 1, 4,red);
            anim.jLabelXLeft(lightBlue.getX(), -1000, 1, 4,lightBlue);
            anim.jLabelYDown(skin.getY(), 1000, 1, 4,skin);
            anim.jLabelXRight(darkBlue.getX(), 1000, 1, 4,darkBlue);
            anim.jLabelYUp(yellow.getY(), -1000, 1, 4,yellow);
            
            anim.jLabelYUp(loginHeading.getY(), -50000, 1, 4, loginHeading);
            anim.jLabelXLeft(usernameLabel.getX(), -50000, 1, 4,usernameLabel);
            anim.jTextFieldXLeft(userNameJTextField.getX(), -50000, 1, 4,userNameJTextField);
            
            anim.jLabelXRight(passwordLabel.getX(), 1000, 1, 4,passwordLabel);
            anim.jTextFieldXRight(passwordField.getX(), 1000, 1, 4,passwordField);
            anim.jButtonYDown(loginBtn.getY(), 1000, 1, 4,loginBtn);
            anim.jButtonYDown(cancelBtn.getY(), 1000, 1, 4,cancelBtn);
            int delay = 600; //milliseconds
            ActionListener taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    frame.setVisible(false);
                    mainJFrame.loggedIn(userAccount,inOrganization,inEnterprise, networkEmergency);
                }
            };
            javax.swing.Timer tick=new javax.swing.Timer(delay,taskPerformer);
            tick.setRepeats(false);
            tick.start();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        userNameJTextField.setText("");
        passwordField.setText("");
        frame.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               JFrame frame = new loginJFrame(system,mainJFrame);
               frame.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel darkBlue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lightBlue;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginHeading;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel red;
    private javax.swing.JLabel skin;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel yellow;
    // End of variables declaration//GEN-END:variables
}
